AllCops:
  TargetRubyVersion: 3.3

plugins:
  - rubocop-numbered-params
  - rubocop-rake
  - rubocop-rbs_inline
  - rubocop-rspec

Style/Documentation:
  Enabled: false

Style/RbsInline/MissingTypeAnnotation:
  EnforcedStyle: doc_style_and_return_annotation

Style/RbsInline/RedundantTypeAnnotation:
  EnforcedStyle: doc_style_and_return_annotation

Style/RbsInline/RequireRbsInlineComment:
  EnforcedStyle: never

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/BlockLength:
  Exclude:
    - "spec/**/*_spec.rb"

Layout/LeadingCommentSpace:
  AllowRBSInlineAnnotation: true
  AllowSteepAnnotation: true

Layout/LineLength:
  Max: 120

Layout/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20

RSpec/ExampleLength:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false
