AllCops:
  TargetRubyVersion: 3.3

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/BlockLength:
  Exclude:
    - "spec/**/*_spec.rb"

Layout/LeadingCommentSpace:
  AllowRBSInlineAnnotation: true
  AllowSteepAnnotation: true

Layout/LineLength:
  Max: 120

Layout/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20
